clientes = input("Nome do cliente: ")
contato = input("Contato: - Digite com o DDD!- ")
tercnico = input("Nome do tecnico: ")

relato = input("Problema relatado pelo cliente: ")
print( )
print( )
print( )
doagnostico = input("Diagnostico: ")
print( )
print( )
print( )
observacao = input("Observações: ")
print( )
print( )
print( )
print("T.TEC Assistencia Técnica de Computadores!\nObrigado pela preferência!")